### ISSUE TITLE
I don't think so

### ISSUE THREAD

**Issue by Vision-dong** [mas-mirror/pics#1]
You should put more black history of CSB, AND IS NOT ME!

**Comment by mtr-static-official** [comment]
> 
> 
> You should put more black history of CSB, AND IS NOT ME!

可以。但是需要你提供csb的黑历史截图（如喝jy那个）

**Comment by Vision-dong** [comment]
sure，让我康康

**Comment by mtr-static-official** [comment]
> 
> 
> sure，让我康康

已收到图片。

**Comment by mtr-static-official** [comment]
> 
> 
> sure，让我康康

注意，注意。我只是**关闭**了这个Issues————不是删除。如果我**想**，那么你的Issues将会永久删除。你可以自行重新open这个Issues。
